config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "flights#index"

  resources :flights
  resources :bookings
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: :departure_airport_id, class_name: "Flight"
  has_many :arriving_flights, foreign_key: :arrival_airport_id, class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers
  belongs_to :flight

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"

  has_many :bookings
  has_many :passengers, through: :bookings

  def self.return_flights(params)
    where(departure_airport_id: params[:departure_airport_id],
      arrival_airport_id: params[:arrival_airport_id],
      departure_date: params[:departure_date])
  end

  def info
      "From #{Airport.find(departure_airport_id).city}, #{Airport.find(departure_airport_id).code} to #{Airport.find(arrival_airport_id).city}, #{Airport.find(arrival_airport_id).code}. Departure on #{departure_date} at #{departure_time.strftime("%H:%M")}. Total flight duration is #{(departure_time + duration).strftime("%Hh%Mm")}"
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @passenger = booking_params[:passengers_attributes]
    respond_to do |format|
      if @booking.save
        Passenger.where(booking_id: @booking).each do |passenger|
          PassengerMailer.with(passenger: passenger).confirm_booking.deliver_now!
        end
        format.html { redirect_to @booking, notice: "Your flight is booked!" }
        format.json { render json: @passenger, status: :created, location: @passenger }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: %i[name email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @search_flights = Flight.all.return_flights(search_params)
    @passenger_num = search_params[:passenger_num]
  end

  private

  def search_params
    params.permit(:departure_airport_id, :arrival_airport_id, :departure_date, :passenger_num, :commit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<div>
    <%= render "shared/search_form" %>
</div>

<div>
    <%= @flight.info %>.
</div>

<div>
    Your Flight ID is <%= params[:flight_id] %>.
</div><br />

<p>Passenger info:</p>
    <%= form_with model: @booking, :html => {:id => "passenger"} do |f|%>
        <% params[:passenger_num].to_i.times do %>

            <%= f.fields_for :passengers, @booking.passengers.build do |p| %>
                <div id="passenger-field" data-controller="passenger" data-passenger-target="template" style="display:flex; margin:15px">
                    <div>
                        <%= p.label :name %>
                        <%= p.text_field :name, placeholder: "John Doe" %>
                    </div>
                    <div>
                        <%= p.label :email %>
                        <%= p.email_field :email, placeholder: "email@domain.com" %>
                    </div>
                    <button data-controller="passenger" data-passenger-target="remove" type="button" id="remove" data-action="passenger#remove">Remove passenger</button>
                </div>
                    <template data-controller="passenger" >
                        <div id="passenger-field" data-passenger-target="template" style="display:flex; margin:15px">
                            <div>
                                <%= p.label :name %>
                                <%= p.text_field :name, placeholder: "John Doe" %>
                            </div>
                            <div>
                                <%= p.label :email %>
                                <%= p.email_field :email, placeholder: "email@domain.com" %>
                            </div><br />
                            <button data-controller="passenger" data-passenger-target="remove" type="button" id="remove" data-action="passenger#remove">Remove passenger</button>
                        </div>
                    </template>
                </div>
            <% end %>
        <%= f.hidden_field :flight_id, value: params[:flight_id] %>
    <% end %>
    <div data-controller="passenger">
        <button data-passenger-target="add" data-action="passenger#add" type="button">Add passenger</button>
    </div><br />
    <%= f.submit "Confirm Booking" %>
<% end %>

app/views/bookings/show.html.erb
<div>
    <%= render "shared/search_form" %>
</div>

<div>
    <%= Flight.find(@booking.flight_id).info %>
</div><br />
<div>
    <% @booking.passengers.each_with_index do |b, idx| %>
        <div>
            <%= "Passenger #{idx + 1}." %><br />
            <%= b.name %><br />
            <%= b.email %>
        </div><br />
    <% end %>
</div>

app/views/flights/index.html.erb
<div>
    <%= render "shared/search_form" %>
</div>

<% if @search_flights.empty? %>
  <div>
    Available flights will appear here
  </div>
<% else %>
  <%= form_with url: new_booking_url, method: :get do |form|%>
    <%= form.collection_radio_buttons :flight_id, @search_flights, :id, :info do |b| %>
      <div>
        <%= b.radio_button %>
        <%= b.label %>
      </div>
    <% end %>
      <%= form.hidden_field :passenger_num, value: @passenger_num %>
    <%= form.submit "Book flight" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_search_form.html.erb
<%= form_with url: "/flights", method: :get do |form| %>

    <%= form.collection_select :departure_airport_id, Airport.order(:name), :id, :code %>
    to
    <%= form.collection_select :arrival_airport_id, Airport.order(:name), :id, :code %>
    Passengers:
    <%= form.select :passenger_num, 1..4 %>
    Departing on
    <%= form.select :departure_date, Time.current.to_date..Time.current.advance(years: +0.3).to_date %>
  <%= form.submit "Search" %>
<% end %><br />